// AUTO-GENERATED by scripts/sync-tokens.ts — do not edit by hand.
// Run `npm run prerender` to regenerate from app/src/app/globals.css.

export const T = {
  primary: '#d97757',
  accent: '#6a9bcc',
  panelBg: '#faf9f5',
  editorBg: '#f0efeb',
  background: '#f5f5f0',
  foreground: '#141413',
  muted: '#b0aea5',
  border: '#e8e6dc',
  green: '#788c5d',

  // Brand wordmark gradient stops
  wordmark1: '#9E5535',
  wordmark2: '#B5613C',
  wordmark3: '#F5DEB3',
  wordmark4: '#F2D49B',
  bullIcon: '#A85432',
  bullBg: '#f0e6d3',

  // /create page gradient
  createGrad1: '#e8edf8',
  createGrad2: '#f0eff8',
  createGrad3: '#f5f4f0',

  // Chart palette (warm theme)
  chartA: '#d97757',
  chartB: '#8b6f4e',
  chartC: '#a89372',
  chartD: '#6b6a65',
  chartE: '#b0aea5',
  chartF: '#e8a87c',

  // Confetti
  confetti: ['#ffe066', '#a0d8ff', '#c4b5fd', '#fda4af'] as const,
} as const;

export const FONTS_DETECTED = [
  'Caveat',
  'Fraunces',
  'Bricolage Grotesque',
  'Plus Jakarta Sans',
  'Inter',
  'Lora',
];

// Composition timing (seconds → frames @ 30fps)
export const FPS = 30;
export const s = (sec: number) => Math.round(sec * FPS);

export const SCENES = {
  intro: { start: 0, end: 3 },
  prompt: { start: 3, end: 10 },
  building: { start: 10, end: 12 },
  streaming: { start: 12, end: 19 },
  chatPolish: { start: 19, end: 29 },
  output: { start: 29, end: 43 },
  close: { start: 43, end: 50 },
} as const;

export const TOTAL_DURATION_SECONDS = 50;
export const TOTAL_FRAMES = s(TOTAL_DURATION_SECONDS);
