#!/usr/bin/env tsx
/**
 * Sync Lasca's design tokens from app/src/app/globals.css -> video/src/lib/tokens.ts.
 * Run as `npm run prerender`. Output file is checked into git.
 */
import fs from 'node:fs';
import path from 'node:path';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SRC_CSS = path.join(REPO_ROOT, 'app', 'src', 'app', 'globals.css');
const OUT_TS = path.join(__dirname, '..', 'src', 'lib', 'tokens.ts');

const COLOR_KEY_MAP: Record<string, string> = {
  primary: 'primary',
  accent: 'accent',
  background: 'background',
  foreground: 'foreground',
  muted: 'muted',
  border: 'border',
  green: 'green',
  'panel-bg': 'panelBg',
  'editor-bg': 'editorBg',
};

function extractColors(css: string): Record<string, string> {
  const out: Record<string, string> = {};
  const re = /--color-([\w-]+):\s*([^;]+);/g;
  let match: ReturnType<RegExp['exec']>;
  while ((match = re.exec(css)) !== null) {
    const cssKey = match[1].trim();
    const value = match[2].trim();
    const tsKey = COLOR_KEY_MAP[cssKey];
    if (tsKey && /^#[0-9a-fA-F]{3,8}$/.test(value)) {
      out[tsKey] = value.toLowerCase();
    }
  }
  return out;
}

function extractFonts(css: string): string[] {
  const re = /--font-[\w-]+:\s*([^;]+);/g;
  const found = new Set<string>();
  let match: ReturnType<RegExp['exec']>;
  while ((match = re.exec(css)) !== null) {
    const stack = match[1];
    const firstFamily = stack
      .split(',')[0]
      .trim()
      .replace(/^["']|["']$/g, '');
    if (firstFamily && !firstFamily.startsWith('var(') && !firstFamily.startsWith('--')) {
      found.add(firstFamily);
    }
  }
  return [...found].sort();
}

function main() {
  if (!fs.existsSync(SRC_CSS)) {
    console.warn(`[sync-tokens] ${SRC_CSS} not found; leaving tokens.ts unchanged.`);
    return;
  }

  const css = fs.readFileSync(SRC_CSS, 'utf8');
  const colors = extractColors(css);
  const fonts = extractFonts(css);

  const required = [
    'primary',
    'accent',
    'background',
    'foreground',
    'muted',
    'border',
    'green',
    'panelBg',
    'editorBg',
  ];

  const missing = required.filter((k) => !colors[k]);
  if (missing.length > 0) {
    console.warn(`[sync-tokens] missing color tokens (kept fallback): ${missing.join(', ')}`);
  }

  const expectedFonts = ['Caveat', 'Fraunces', 'Bricolage Grotesque', 'Plus Jakarta Sans', 'Inter'];
  const newFonts = fonts.filter((f) => !expectedFonts.includes(f));
  if (newFonts.length > 0) {
    console.warn(
      `[sync-tokens] new font families detected in globals.css; consider adding loaders in src/lib/fonts.ts: ${newFonts.join(', ')}`
    );
  }

  const body = `// AUTO-GENERATED by scripts/sync-tokens.ts -- do not edit by hand.
// Run \`npm run prerender\` to regenerate from app/src/app/globals.css.

export const T = {
  primary: '${colors.primary ?? '#d97757'}',
  accent: '${colors.accent ?? '#6a9bcc'}',
  panelBg: '${colors.panelBg ?? '#faf9f5'}',
  editorBg: '${colors.editorBg ?? '#f0efeb'}',
  background: '${colors.background ?? '#f5f5f0'}',
  foreground: '${colors.foreground ?? '#141413'}',
  muted: '${colors.muted ?? '#b0aea5'}',
  border: '${colors.border ?? '#e8e6dc'}',
  green: '${colors.green ?? '#788c5d'}',

  // Brand wordmark gradient stops
  wordmark1: '#9E5535',
  wordmark2: '#B5613C',
  wordmark3: '#F5DEB3',
  wordmark4: '#F2D49B',
  bullIcon: '#A85432',
  bullBg: '#f0e6d3',

  // /create page gradient
  createGrad1: '#e8edf8',
  createGrad2: '#f0eff8',
  createGrad3: '#f5f4f0',

  // Chart palette (warm theme)
  chartA: '#d97757',
  chartB: '#8b6f4e',
  chartC: '#a89372',
  chartD: '#6b6a65',
  chartE: '#b0aea5',
  chartF: '#e8a87c',

  // Confetti
  confetti: ['#ffe066', '#a0d8ff', '#c4b5fd', '#fda4af'] as const,
} as const;

export const FONTS_DETECTED = ${JSON.stringify(fonts.length > 0 ? fonts : expectedFonts, null, 2)};

// Composition timing (seconds -> frames @ 30fps)
export const FPS = 30;
export const s = (sec: number) => Math.round(sec * FPS);

export const SCENES = {
  intro: { start: 0, end: 4 },
  prompt: { start: 4, end: 12 },
  building: { start: 12, end: 22 },
  streaming: { start: 22, end: 38 },
  chatPolish: { start: 38, end: 48 },
  output: { start: 48, end: 54 },
  close: { start: 54, end: 60 },
} as const;

export const TOTAL_DURATION_SECONDS = 60;
export const TOTAL_FRAMES = s(TOTAL_DURATION_SECONDS);
`;

  fs.writeFileSync(OUT_TS, body, 'utf8');
  console.log(
    `[sync-tokens] wrote ${path.relative(REPO_ROOT, OUT_TS)} - ${Object.keys(colors).length} colors, ${fonts.length} fonts detected`
  );
}

main();
